<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by TablePlus 3.12.8(369)
 * @author https://tableplus.com
 * @source https://github.com/TablePlus/tabledump
 */
class CreateWbsSenderTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('wbs_sender', function (Blueprint $table) {
            $table->bigInteger('id')->unsigned()->autoIncrement();
            $table->string('name', 255);
            $table->string('email', 255)->unique();
            $table->string('phone', 255);
            $table->timestamp('email_verified_at')->nullable()->default(NULL);
            $table->string('url_token', 255)->nullable()->default(NULL);
            $table->string('old_url_token', 255)->nullable()->default(NULL);
            $table->timestamp('created_at')->nullable()->default(NULL);
            $table->timestamp('updated_at')->nullable()->default(NULL);
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('wbs_sender');
    }
}
