<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by TablePlus 3.12.6(367)
 * @author https://tableplus.com
 * @source https://github.com/TablePlus/tabledump
 */
class CreatePostsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('posts', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement();
            $table->bigInteger('author_id');
            $table->string('slug', 255)->nullable()->default(NULL);
            $table->text('seo_meta_description')->nullable()->default(NULL);
            $table->text('excerpt')->nullable()->default(NULL);
            $table->text('title');
            $table->longtext('content')->nullable()->default(NULL);
            $table->text('seo_index')->nullable()->default(NULL);
            $table->text('featured_image')->nullable()->default(NULL);
            $table->string('type', 255)->nullable()->default(NULL);
            $table->string('status', 255)->nullable()->default(NULL);
            $table->datetime('created_at')->nullable()->default(NULL);
            $table->datetime('updated_at')->nullable()->default(NULL);
            $table->bigInteger('updated_by')->nullable()->default(NULL);
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('posts');
    }
}
