<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by TablePlus 3.12.6(367)
 * @author https://tableplus.com
 * @source https://github.com/TablePlus/tabledump
 */
class CreateCategoriesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('categories', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement();
            $table->string('slug', 255)->nullable()->default(NULL);
            $table->text('title')->nullable()->default(NULL);
            $table->text('description')->nullable()->default(NULL);
            $table->text('icon')->nullable()->default(NULL);
            $table->datetime('created_at')->nullable()->default(NULL);
            $table->datetime('updated_at')->nullable()->default(NULL);
            $table->bigInteger('created_by')->nullable()->default(NULL);
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('categories');
    }
}
