<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by TablePlus 3.12.6(367)
 * @author https://tableplus.com
 * @source https://github.com/TablePlus/tabledump
 */
class CreateCategoryRelationshipsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('category_relationships', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement();;
            $table->bigInteger('post_id')->nullable()->default(NULL);
            $table->bigInteger('category_id')->nullable()->default(NULL);
            $table->datetime('created_at')->nullable()->default(NULL);
            $table->datetime('updated_at')->nullable()->default(NULL);
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('category_relationships');
    }
}
