<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by TablePlus 3.12.8(369)
 * @author https://tableplus.com
 * @source https://github.com/TablePlus/tabledump
 */
class CreateWbsFeedbackTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('wbs_feedback', function (Blueprint $table) {
            $table->bigInteger('id')->unsigned()->autoIncrement();
            $table->bigInteger('user_id')->nullable()->default(NULL);
            $table->string('title', 255);
            $table->longtext('content')->nullable()->default(NULL);
            $table->text('file')->nullable()->default(NULL);
            $table->string('type', 255)->nullable()->default(NULL);
            $table->string('status', 255)->nullable()->default(NULL);
            $table->string('url_token', 255)->nullable()->default(NULL);
            $table->timestamp('created_at')->nullable()->default(NULL);
            $table->timestamp('updated_at')->nullable()->default(NULL);
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('wbs_feedback');
    }
}
